### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by kerharhun45** [MEEPofFaith/bottom-left-UI#1]
Hello!
I have a problem: on mindustry android mindustry release build 146 the game crashes instantly if i use this mod. I think it was a really good idea to create this mod, because I'm left handed. So i'd like to try it. Thank you in advance for your help!

**Comment by MEEPofFaith** [comment]
Send crash report, I cannot fix if I don't know what to fix.

**Comment by kerharhun45** [comment]
[kerhar45_crash_1.zip](https://github.com/MEEPofFaith/bottom-left-UI/files/15119208/kerhar45_crash_1.zip)
This is my ceash report. I compressed it to .zip because github hasn't allowed me to upload in .bin.

**Comment by MEEPofFaith** [comment]
new release fixes this
